web/config/routes.rb
Rails.application.routes.draw do
  post 'transactions/reset_all' => 'transactions#reset_all', as: :reset_all
  post 'transactions/toggle_producer' => 'transactions#toggle_producer', as: :toggle_producer
  post 'transactions/start_all_producers' => 'transactions#start_all_producers', as: :start_all_producers
  post 'transactions/stop_all_producers' => 'transactions#stop_all_producers', as: :stop_all_producers
  resources :transactions, only: [:index]
end

web/app/models/account.rb
class Account < ApplicationRecord
  enum account_type: { bank: 'bank', user: 'user' }

  has_many :tranferrer_transactions, class_name: 'Transaction', foreign_key: 'transferrer_account_id'
  has_many :receiver_transactions, class_name: 'Transaction', foreign_key: 'receiver_account_id'

  def Account.bank_account
    self.where(account_type: :bank).first
  end
end

web/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

web/app/models/transaction.rb
class Transaction < ApplicationRecord
  enum transaction_type: { topup: 'topup', payment: 'payment' }
  enum status: { success: 'success', fail: 'fail' }

  belongs_to :transferrer_account, class_name: 'Account', foreign_key: 'transferrer_account_id'
  belongs_to :receiver_account, class_name: 'Account', foreign_key: 'receiver_account_id'
end

web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

web/app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  NO_OF_PRODUCERS = ENV['NO_OF_PRODUCERS']&.to_i || 3
  MIN_INITIAL_BALANCE = ENV['MIN_INITIAL_BALANCE']&.to_i || 0
  MAX_INITIAL_BALANCE = ENV['MAX_INITIAL_BALANCE']&.to_i || 100

  def index
    @accounts = Account.order('id asc').all&.map do |acc|
      {
          id: acc.id,
          account_type: acc.account_type,
          balance: acc.balance,
          is_on: ($redis.get("producer.#{acc.id}.is_on") == "true")
      }.with_indifferent_access
    end
    @transactions = Transaction.order('id desc').limit(50)
  end

  def toggle_producer
    producer_id = params['producer_id']

    original = $redis.get("producer.#{producer_id}.is_on")
    $redis.setex("producer.#{producer_id}.is_on", 7.days, original == "true" ? false : true)

    redirect_back fallback_location: :index
  end

  def start_all_producers
    NO_OF_PRODUCERS.times do |i|
      $redis.setex("producer.#{i + 2}.is_on", 7.days, true)
    end

    redirect_back fallback_location: :index
  end

  def stop_all_producers
    NO_OF_PRODUCERS.times do |i|
      $redis.setex("producer.#{i + 2}.is_on", 7.days, false)
    end

    redirect_back fallback_location: :index
  end

  def reset_all
    Transaction.delete_all
    ActiveRecord::Base.connection.reset_pk_sequence!(Transaction.table_name)

    bank_account = Account.bank_account
    bank_account.update!(balance: 0)

    Account.all.each do |acc|
      next if acc.bank?

      initial_balance = rand(MIN_INITIAL_BALANCE..MAX_INITIAL_BALANCE)

      bank_new_balance = bank_account.balance - initial_balance
      bank_account.update!(balance: bank_new_balance)
      acc.update!(balance: initial_balance)

      Transaction.create!(
          transferrer_account: Account.bank_account,
          receiver_account: acc,
          transaction_type: Transaction.transaction_types[:topup],
          amount: initial_balance,
          status: Transaction.statuses[:success],
          transferrer_balance: bank_new_balance,
          receiver_balance: initial_balance
      )
    end

    redirect_back fallback_location: :index
  end
end

web/app/helpers/application_helper.rb
module ApplicationHelper
end

web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiServer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

web/app/views/transactions/index.html.erb
(This page auto-refreshes every 3 sec)
<h1>Accounts</h1>

<%= link_to "Start all producers", start_all_producers_path, method: :post %>
<br>
<%= link_to "Stop all producers", stop_all_producers_path, method: :post %>
<br>

<table border="1">
  <thead>
  <tr>
    <th>ID</th>
    <th>Balance</th>
    <th>Account Type</th>
    <th>Is ON?</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @accounts.each do |acc| %>
    <tr>
      <td><%= acc['id'] %></td>
      <td><%= acc['balance'] %></td>
      <td><%= acc['account_type'] %></td>
      <td><%= acc['is_on'] %></td>
      <td><%= button_to("Toggle On/Off", toggle_producer_path, method: :post, params: { producer_id: acc['id'] }) unless acc['account_type'] == Account.account_types[:bank] %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to "Reset all (Clear transactions and assign random positive balance)", reset_all_path, method: :post %>
<br>

<h1>Last 50 Transactions</h1>

<table border="1">
  <thead>
  <tr>
    <th>ID</th>
    <th>Transferrer ID</th>
    <th>Receiver ID</th>
    <th>Transaction Type</th>
    <th>Amount</th>
    <th>Transferrer Balance</th>
    <th>Receiver Balance</th>
    <th>Status</th>
  </tr>
  </thead>

  <tbody>
  <% @transactions.each do |t| %>
    <tr>
      <td><%= t.id %></td>
      <td><%= t.transferrer_account_id %></td>
      <td><%= t.receiver_account_id %></td>
      <td><%= t.transaction_type %></td>
      <td><%= t.amount %></td>
      <td><%= t.transferrer_balance %></td>
      <td><%= t.receiver_balance %></td>
      <td><%= t.status %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<script>
    function timedRefresh(timeoutPeriod) {
        setTimeout("location.reload(true);", timeoutPeriod);
    }
</script>

<body onload="JavaScript:timedRefresh(3000);">